#ddev-generated
# Simple template to demonstrate addon-template
services:
  stripe:
    container_name: ddev-${DDEV_SITENAME}-stripe
    image: stripe/stripe-cli
    networks: [default, ddev_default]
    restart: "no"
    env_file:
      - .env
    command: listen --api-key "${STRIPE_API_KEY}" --forward-to "${WEBHOOK_SERVICE_NAME}":"${WEBHOOK_SERVICE_PORT}"/"${WEBHOOK_ENDPOINT}"
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT

networks:
  ddev_default:
    external: true
